# -*- coding: utf-8 -*-
"""rete neurale monodimensionale (temperature)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IDtap_WI_u8Q2zy7qvxFCC_uayTnGRU5
"""

import torch

x = torch.tensor(
    [55, 65, 75, 54, 67, 78, 53, 65, 76, 60, 70, 81, 51, 68],
    dtype=torch.float32
).unsqueeze(1)
y = torch.tensor(
    [13, 18, 24, 12, 20, 26, 12, 18, 24, 14, 21, 28, 12, 20],
    dtype=torch.float32
).unsqueeze(1)

x.shape

from matplotlib import pyplot
pyplot.scatter(x,y)

torch.manual_seed(42)

model = torch.nn.Linear(1, 1)
loss_fn = torch.nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.1)

model(x)

for epoch in range(3000):
  optimizer.zero_grad()
  y_pred = model(x)
  loss = loss_fn(y_pred, y)
  loss.backward()
  optimizer.step()
  if epoch % 100 == 0:
    print(f"Epoch {epoch}, Loss: {loss}")
  if epoch in [0, 2, 4, 100, 2999]:
    pyplot.plot(x, y_pred.detach(), label=f"Epoch: {epoch}")
pyplot.scatter(x, y)
pyplot.legend()

current_temperature = torch.tensor([70], dtype=torch.float32)
model(current_temperature)
for param in model.parameters():
  print(param)